# Generated by Django 3.0.1 on 2019-12-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prosignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('mobile', models.IntegerField(verbose_name=10)),
                ('pincode', models.IntegerField(verbose_name=6)),
                ('experience', models.IntegerField(verbose_name=2)),
                ('website', models.CharField(max_length=30)),
                ('expertin', models.CharField(max_length=30)),
                ('Fk_Login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homecareapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Customersignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.IntegerField(verbose_name=10)),
                ('pincode', models.IntegerField(verbose_name=6)),
                ('Fk_Login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homecareapp.Login')),
            ],
        ),
    ]
